// packages
export  'package:flutter/material.dart';
export  'package:flutter/services.dart';
export  'package:google_fonts/google_fonts.dart';
export  'package:dropdown_banner/dropdown_banner.dart';
export  'package:hive_flutter/hive_flutter.dart';
export  'package:path_provider/path_provider.dart';
export  'package:hive/hive.dart';
export  'package:provider/provider.dart';
export  'package:flutter_app_testing/theme/theme.dart';
export  'package:badges/badges.dart';
// painter
export  'package:flutter_app_testing/painter/painters.dart';
// clipper
export  'package:flutter_app_testing/clipper/clippers.dart';
// widgets
export  'package:flutter_app_testing/widgets/widgets.dart';
// pages
export  'package:flutter_app_testing/pages/pages.dart';
// animations
export  'package:flutter_app_testing/animation/bouncyPageRoute.dart';
// notifier
export  'package:flutter_app_testing/notifier/ThemeNotifier.dart';